### ISSUE TITLE
Only the top PR is merged 

### ISSUE THREAD

**Issue by Huxpro** [ejoffe/spr#233] opened 2022-04-07 21:58 UTC
<img width="56" alt="image" src="https://user-images.githubusercontent.com/5563315/162326478-e84bb006-0ca6-4d40-b9c3-bdd52075c985.png">

Is this an expected behavior that when you run `git spr merge` to merge a stack, only the top PR is actually "merged" and others are only "closed"? This seems to be very counter intuitive.

**Comment by ejoffe** [comment] 2022-04-07 22:27
This is expected behavior, and needs to be documented better in the readme so it's less surprising. 
When you merge, the top pr is rebased on top of master, and then merged. 
All the commits will be merged at once. Then the rest of the prs are closed. 

Some related discussion: #209 #227

**Comment by anagrius** [comment] 2022-04-10 11:45
I have been very happy with spr, but this is really not the workflow I was hoping for. 
I might use spr slightly differently than intended and having PR's merged individually is much more fitting for me.

I have a large refactoring effort, and there is always substantial delay between I make a contribution to it being reviewed. I would like to build on previous changes to the review delay does not hold me back, and merge the commit one-by-one when they have been reviewed because they are atomic and at times not directly related.

The merge --upto method works, but it would be nice to just have it be a setting.

SPR has changed my daily workflow for the better, and I would love to help in any way I can.

**Comment by ejoffe** [comment] 2022-04-11 03:46
@anagrius : spr was designed for the exact use case you are experiencing, where you want to keep working on features that build on top of other features, but you don't want to wait for them to merge. 
Just to clarify, when you run 'git spr merge', all the prs that are ready to be merged in the stack are merged. I sometimes have stacks that grow to 10-15 prs, and merging them one by one would be a pain, so personally I like the ability to merge them all at once in one shot. 
Have said that, it sounds like you are not alone in wanting to merge prs one by one, for a similar feature enhancement request see #231

**Comment by ejoffe** [comment] 2022-05-18 09:59
@anagrius - how about we add a flag --one that only merges one pr?

**Comment by ejoffe** [comment] 2022-06-04 01:38
Added a new flag --count or -c. Now this can be easily achieved with:
`git spr merge -c 1`

**Closed** 2022-06-04 06:50 UTC
Labels: enhancement
